In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,"abc"]

In [3]:
type(l)

list

In [5]:
np.array(l)

##dtype='<U21' --> string object

array(['1', '2', '3', '4', '5', 'abc'], dtype='<U21')

In [7]:
type(np.array(l))

numpy.ndarray

In [8]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [11]:
#2D array
np.array([[1,2,3,4],[445,56,67,78]])

array([[  1,   2,   3,   4],
       [445,  56,  67,  78]])

In [12]:
np.array([[1,2,3,4]], ndmin=4)

#ndmin=4 --> parameter will take numeric value and convert into dimentions
#ndmin=4 --> 4 dimension array


array([[[[1, 2, 3, 4]]]])

In [14]:
np.mat([1,2,3])
#convert into matrix format

matrix([[1, 2, 3]])

In [15]:
arr = np.array([1,2,3,4,5,6])

In [16]:
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
arr[0]

1

In [18]:
arr[5]

6

In [19]:
arr[0:3]

array([1, 2, 3])

In [21]:
arr[0:5:2]
#starting from 0 got till 5th element, get every 2nd element

array([1, 3, 5])

In [22]:
arr[-1]

6

In [23]:
arr[0:-2]

array([1, 2, 3, 4])

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [25]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1[1][-1]

6

In [27]:
arr1[1][2]

6

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0][2]

3

In [5]:
arr[1][-1]

6

In [6]:
arr[1][2]

6

In [7]:
arr[2][2]

9

In [8]:
arr[2,2]

9

In [10]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [12]:
np.asarray([1,2,3,4], dtype=np.float32)
#it will able to convert all the integert element into float

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [15]:
np.asanyarray(np.mat([1,2,3]))

#array matrix is already one of the format of array so it is not able to convert into array

matrix([[1, 2, 3]])

## np.fromfunction()

np.fromfunction(
    function,
    shape,
    *,
    dtype=<class 'float'>,
    like=None,
    **kwargs,
)
Docstring:
Construct an array by executing a function over each coordinate.

The resulting array therefore has a value ``fn(x, y, z)`` at
coordinate ``(x, y, z)``.

Parameters
----------
function : callable
    The function is called with N parameters, where N is the rank of
    `shape`.  Each parameter represents the coordinates of the array
    varying along a specific axis.  For example, if `shape`
    were ``(2, 2)``, then the parameters would be
    ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    
shape : (N,) tuple of ints
    Shape of the output array, which also determines the shape of
    the coordinate arrays passed to `function`.
    
dtype : data-type, optional
    Data-type of the coordinate arrays passed to `function`.
    By default, `dtype` is float.
    
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
fromfunction : any
    The result of the call to `function` is passed back directly.
    Therefore the shape of `fromfunction` is completely determined by
    `function`.  If `function` returns a scalar value, the shape of
    `fromfunction` would not match the `shape` parameter.

See Also
--------
indices, meshgrid

Notes
-----
Keywords other than `dtype` are passed to `function`.

Examples
--------
    >>> np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
    array([[ True, False, False],
           [False,  True, False],
           [False, False,  True]])

    >>> np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
    array([[0, 1, 2],
           [1, 2, 3],
           [2, 3, 4]])
    File:      ~/anaconda3/lib/python3.8/site-packages/numpy/core/numeric.py
    Type:      function

In [18]:
np.fromfunction(lambda x, y : x*y, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [20]:
np.fromfunction(lambda x, y : x*y, (4,4), dtype=int)

#x*y --> multiplication of dimentions 
#x --> row, y--> column, of shape(4,4), datatype = int

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

      y     0 1 2 3  
      x  0 [0,0,0,0]
         1 [0,1,2,3]
         2 [0,2,4,6]
         3 [0,3,6,9]

In [21]:
np.fromfunction(lambda x, y : x+y, (4,4), dtype=int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [22]:
np.fromfunction(lambda x, y, z : x+y+z, (4,4), dtype=int)

TypeError: <lambda>() missing 1 required positional argument: 'z'

In [28]:
#need to provide 3 dimension shape
np.fromfunction(lambda x, y, z : x+y+z, (3,3,2), dtype=int)

#x+y+z --> summation of dimentions
#3*2 arrays and 3 such arrays of (3*2)

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [29]:
np.fromfunction(lambda x, y, z : x+y+z, (3,3,1), dtype=int)

array([[[0],
        [1],
        [2]],

       [[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]])

## np.fromiter()


fromiter(iter, dtype, count=-1, *, like=None)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iter : iterable object
    An iterable object providing data for the array.
    
dtype : data-type
    The data-type of the returned array.
    
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.
    
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance.  It allows ``fromiter`` to
pre-allocate the output array, instead of resizing it on demand.

Examples
--------
    >>> iterable = (x*x for x in range(5))
    >>> np.fromiter(iterable, float)
    array([  0.,   1.,   4.,   9.,  16.])
    Type:      builtin_function_or_method

In [32]:
for i in 5:
    print(i)
    
#TypeError: 'int' object is not iterable

TypeError: 'int' object is not iterable

In [34]:
for i in "xyz":
    print(i)

x
y
z


In [35]:
for i in "a":
    print(i)

a


In [36]:
for i in [1,2,3]:
    print(i)

1
2
3


In [6]:
import numpy as np

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#!pip install --upgrade notebook


In [1]:
s = "abc"
next(s)

TypeError: 'str' object is not an iterator

## Python Iterators

An iterator is an object that contains a countable number of values.

An iterator is an object that can be iterated upon, meaning that you can traverse through all the values.

Technically, in Python, an iterator is an object which implements the iterator protocol, which consist of the methods __iter__() and __next__().

Iterator vs Iterable
Lists, tuples, dictionaries, and sets are all iterable objects. They are iterable containers which you can get an iterator from.

All these objects have a iter() method which is used to get an iterator:

## Python | Difference between iterable and iterator


Iterable is an object, which one can iterate over. It generates an Iterator when passed to iter() method. Iterator is an object, which is used to iterate over an iterable object using __next__() method. Iterators have __next__() method, which returns the next item of the object.

Note that every iterator is also an iterable, but not every iterable is an iterator. For example, a list is iterable but a list is not an iterator. An iterator can be created from an iterable by using the function iter(). To make this possible, the class of an object needs either a method __iter__, which returns an iterator, or a __getitem__ method with sequential indexes starting with 0.

    for city in ["Berlin", "Vienna", "Zurich"]:
        print(city)

    print("\n")

    for city in ("Python", "Perl", "Ruby"):
        print(city)

    print("\n")

    for char in "Iteration is easy":
        print(char, end = " ")
        
        
        Berlin
        Vienna
        Zurich

        Python
        Perl
        Ruby

        I t e r a t i o n   i s   e a s y 
        



In [2]:
l = [1,2,3]

In [3]:
next(l)

TypeError: 'list' object is not an iterator

In [4]:
r =range(4)

In [5]:
next(r)

TypeError: 'range' object is not an iterator

In [6]:
i = iter(s)

In [7]:
next(i)

'a'

In [8]:
next(i)

'b'

In [9]:
next(i)

'c'

In [10]:
next(i)

StopIteration: 

In [11]:
for i in "abcde":
    print(i)

a
b
c
d
e


In [13]:
#If a object is itable object then "iter" function convert iterable object into iterator 
#this is what for loop does

l = [1,2,3,4,5,"abc"]
for i in l:
    print(i)

1
2
3
4
5
abc


In [24]:
next(l)

TypeError: 'list' object is not an iterator

In [19]:
i=iter(l)

In [20]:
next(i)

1

In [21]:
next(i)

2

In [22]:
next(i)

3

In [23]:
next(i)

4

In [26]:
import numpy as np
np.fromiter([1,2,3,4,5], dtype=int)

array([1, 2, 3, 4, 5])

In [29]:
np.fromstring("abcxyz", sep=",")
#suppose to pass the numerical value 

/tmp/ipykernel_97581/1386508469.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("abcxyz", sep=",")


array([], dtype=float64)

In [30]:
np.fromstring("1 2 3", sep=" ")

array([1., 2., 3.])

In [31]:
np.fromstring("100 2546 363546546", sep=" ")

array([1.00000000e+02, 2.54600000e+03, 3.63546546e+08])

In [32]:
np.fromstring("100 2546 363546546", dtype=int, sep=" ")

array([      100,      2546, 363546546])

In [33]:
l = [1,2,3,4,5,6]

In [34]:
arr = np.array(l)

In [35]:
arr

array([1, 2, 3, 4, 5, 6])

In [37]:
#ndim will show the number of dimention
arr.ndim

1

In [39]:
#size will return size of the array
arr.size

6

In [42]:
 #shape will return no of rows and no of column
arr.shape

(6,)

In [48]:
x = np.fromfunction(lambda x, y, z : x+y+z, (3,3,4), dtype=int)

In [49]:
x

array([[[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]],

       [[2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]]])

In [50]:
x.shape

(3, 3, 4)

In [52]:
x.dtype

dtype('int64')

In [53]:
range(0,4)

range(0, 4)

In [55]:
list(range(0,8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [56]:
list(range(0,8.5))

TypeError: 'float' object cannot be interpreted as an integer

## np.arange()

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
    
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
    
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``.  The default
    step size is 1.  If `step` is specified as a position argument,
    `start` must also be given.
    
dtype : dtype
    The type of the output array.  If `dtype` is not given, infer the data
    type from the other input arguments.
    
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
arange : ndarray
    Array of evenly spaced values.

    For floating point arguments, the length of the result is
    ``ceil((stop - start)/step)``.  Because of floating point overflow,
    this rule may result in the last element of `out` being greater
    than `stop`.

See Also
--------
numpy.linspace : Evenly spaced numbers with careful handling of endpoints.
numpy.ogrid: Arrays of evenly spaced numbers in N-dimensions.
numpy.mgrid: Grid-shaped arrays of evenly spaced numbers in N-dimensions.

Examples
--------
    >>> np.arange(3)
    array([0, 1, 2])
    >>> np.arange(3.0)
    array([ 0.,  1.,  2.])
    >>> np.arange(3,7)
    array([3, 4, 5, 6])
    >>> np.arange(3,7,2)
    array([3, 5])
    Type:      builtin_function_or_method

In [57]:
np.arange(0,4.6)

array([0., 1., 2., 3., 4.])

In [59]:
np.arange(0,4.6, 0.4)
#we can give jump value in float as well

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4])

In [61]:
np.arange(3,7)

array([3, 4, 5, 6])

## np.linspace()

np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
    
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
    
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
    
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
    
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
    
dtype : dtype, optional
    The type of the output array.  If `dtype` is not given, the data type
    is inferred from `start` and `stop`. The inferred dtype will never be
    an integer; `float` is chosen even if the arguments would produce an
    array of integers.

    .. versionadded:: 1.9.0

axis : int, optional
    The axis in the result to store the samples.  Relevant only if start
    or stop are array-like.  By default (0), the samples will be along a
    new axis inserted at the beginning. Use -1 to get an axis at the end.

    .. versionadded:: 1.16.0

Returns
-------
samples : ndarray
    There are `num` equally spaced samples in the closed interval
    ``[start, stop]`` or the half-open interval ``[start, stop)``
    (depending on whether `endpoint` is True or False).
step : float, optional
    Only returned if `retstep` is True

    Size of spacing between samples.


See Also
--------
arange : Similar to `linspace`, but uses a step size (instead of the
         number of samples).
geomspace : Similar to `linspace`, but with numbers spaced evenly on a log
            scale (a geometric progression).
logspace : Similar to `geomspace`, but with the end points specified as
           logarithms.

Examples
--------
    >>> np.linspace(2.0, 3.0, num=5)
    array([2.  , 2.25, 2.5 , 2.75, 3.  ])
    >>> np.linspace(2.0, 3.0, num=5, endpoint=False)
    array([2. ,  2.2,  2.4,  2.6,  2.8])
    >>> np.linspace(2.0, 3.0, num=5, retstep=True)
    (array([2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

    Graphical illustration:

    >>> import matplotlib.pyplot as plt
    >>> N = 8
    >>> y = np.zeros(N)
    >>> x1 = np.linspace(0, 10, N, endpoint=True)
    >>> x2 = np.linspace(0, 10, N, endpoint=False)
    >>> plt.plot(x1, y, 'o')
    [<matplotlib.lines.Line2D object at 0x...>]
    >>> plt.plot(x2, y + 0.5, 'o')
    [<matplotlib.lines.Line2D object at 0x...>]
    >>> plt.ylim([-0.5, 1])
    (-0.5, 1)
    >>> plt.show()
    File:      ~/anaconda3/lib/python3.8/site-packages/numpy/core/function_base.py
    Type:      function

In [62]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [63]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [66]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [67]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [68]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [73]:
x = np.linspace(1,50)

In [74]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [84]:
y = np.linspace(10,50,5)
#start from 10 end at 50, create only 5 element

In [85]:
y

array([10., 20., 30., 40., 50.])

In [90]:
z = np.linspace(1,100,10000)

In [91]:
z

array([  1.        ,   1.00990099,   1.01980198, ...,  99.98019802,
        99.99009901, 100.        ])

In [92]:
z.size

10000

In [93]:
z.shape

(10000,)

In [94]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [97]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [101]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [102]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [103]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [104]:
np.ones((2,5)) + 1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [105]:
 x =np.ones((2,5))

In [106]:
x+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [109]:
x*100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [110]:
x /1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
np.empty((3,2))

array([[  1.        ,   1.00990099],
       [  1.01980198,  99.98019802],
       [ 99.99009901, 100.        ]])

In [115]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.random.rand()

rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]) #random
    Type:      builtin_function_or_method


In [124]:
np.random.rand(3,5,5)

array([[[0.24244584, 0.09374414, 0.48088307, 0.29340797, 0.80476834],
        [0.87918141, 0.452163  , 0.8108207 , 0.50271043, 0.23604851],
        [0.60001967, 0.26491392, 0.13946828, 0.41481894, 0.69703118],
        [0.89530419, 0.87863119, 0.94039062, 0.47107902, 0.06029309],
        [0.94188509, 0.91485711, 0.30588514, 0.45996766, 0.82557434]],

       [[0.29760496, 0.63944441, 0.81142868, 0.90702296, 0.81104186],
        [0.53277786, 0.31103406, 0.41375256, 0.06511225, 0.78406996],
        [0.59256746, 0.21664861, 0.69687917, 0.45243833, 0.38861658],
        [0.8014348 , 0.35442197, 0.12041688, 0.07123611, 0.44728645],
        [0.61955634, 0.19355437, 0.83545416, 0.27270701, 0.33748911]],

       [[0.81199278, 0.47777594, 0.44979953, 0.4765141 , 0.24645179],
        [0.75505971, 0.00902049, 0.58875617, 0.00676518, 0.47033521],
        [0.29644931, 0.55385084, 0.14239454, 0.45047291, 0.56032067],
        [0.66452208, 0.58405048, 0.76734047, 0.77006426, 0.29608538],
        [0.50706

In [126]:
x = np.random.rand(100000,5)

In [127]:
x

array([[0.1579328 , 0.49880144, 0.57156797, 0.84375081, 0.952551  ],
       [0.04398327, 0.7906118 , 0.50551286, 0.98848662, 0.66301641],
       [0.18526792, 0.5742721 , 0.70834738, 0.73601565, 0.51653557],
       ...,
       [0.50271853, 0.02396553, 0.84498501, 0.57770675, 0.81974595],
       [0.24064881, 0.75127834, 0.13153516, 0.44076842, 0.23233018],
       [0.43594484, 0.13498435, 0.94874986, 0.33337671, 0.85573138]])

In [128]:
x.size

500000

In [129]:
x.shape

(100000, 5)

In [131]:
x.ndim

2

## np.random.randn()

randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the ``standard_normal`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
Z : ndarray or float
    A ``(d0, d1, ..., dn)``-shaped array of floating-point samples from
    the standard normal distribution, or a single such float if
    no parameters were supplied.

See Also
--------
standard_normal : Similar, but takes a tuple as its argument.
normal : Also accepts mu and sigma arguments.
Generator.standard_normal: which should be used for new code.

Notes
-----
For random samples from :math:`N(\mu, \sigma^2)`, use:

``sigma * np.random.randn(...) + mu``

Examples
--------
    >>> np.random.randn()
    2.1923875335537315  # random

    Two-by-four array of samples from N(3, 6.25):

    >>> 3 + 2.5 * np.random.randn(2, 4)
    array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677],   # random
           [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])  # random
    Type:      builtin_function_or_method

In [133]:
np.random.randn(4,5)

#Return a sample (or samples) from the "standard normal" distribution.
#mean = 0, standard deviation = 1

array([[-1.13045989,  2.35575734,  0.97346056, -1.74256415, -0.3210678 ],
       [ 1.12249921,  1.874435  ,  0.2513909 , -1.11965752, -1.48781604],
       [-1.85242889,  0.79961365, -1.22288287,  0.82606861, -1.26485283],
       [-0.69216025,  0.26954885,  0.55054117, -0.27352894,  0.72710204]])

## np.random.randint()

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. Byteorder must be native.
    The default value is int.

    .. versionadded:: 1.11.0

Returns
-------
out : int or ndarray of ints
    `size`-shaped array of random integers from the appropriate
    distribution, or a single such random int if `size` not provided.

See Also
--------
random_integers : similar to `randint`, only for the closed
    interval [`low`, `high`], and 1 is the lowest value if `high` is
    omitted.
Generator.integers: which should be used for new code.

Examples
--------
    >>> np.random.randint(2, size=10)
    array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0]) # random
    >>> np.random.randint(1, size=10)
    array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generate a 2 x 4 array of ints between 0 and 4, inclusive:

    >>> np.random.randint(5, size=(2, 4))
    array([[4, 0, 2, 1], # random
           [3, 2, 2, 0]])

Generate a 1 x 3 array with 3 different upper bounds

    >>> np.random.randint(1, [3, 5, 10])
    array([2, 2, 9]) # random

Generate a 1 by 3 array with 3 different lower bounds

    >>> np.random.randint([1, 5, 7], 10)
    array([9, 8, 7]) # random

Generate a 2 by 4 array using broadcasting with dtype of uint8

    >>> np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
    array([[ 8,  6,  9,  7], # random
           [ 1, 16,  9, 12]], dtype=uint8)
    Type:      builtin_function_or_method

In [134]:
np.random.randint(3,4)

3

In [135]:
np.random.randint(3,40, size = 60)

array([ 5, 34, 16, 34, 16, 34, 39,  9,  7, 27,  8, 23,  8, 35, 22,  3, 39,
        3, 32, 19, 10, 27, 26, 15, 18, 36, 32, 27, 23, 12, 18, 19,  3, 33,
       32, 26,  9,  9, 38, 35, 32,  8, 36, 30,  9, 13, 18, 17, 10,  4, 27,
       27, 12, 37,  9, 38, 26, 22, 17, 15])

In [140]:
np.random.randint(3,8,(5,3))
#start from 3 end at 5, shape = 5,3

array([[7, 5, 6],
       [4, 7, 4],
       [6, 4, 5],
       [5, 3, 3],
       [4, 7, 6]])

In [141]:
x = np.random.randint(3,8,(5,3))

In [142]:
x

array([[4, 4, 5],
       [6, 6, 5],
       [4, 4, 6],
       [5, 4, 3],
       [3, 5, 6]])

In [143]:
x.shape

(5, 3)

In [144]:
x.size

15

In [145]:
x.reshape(1,5,3)

array([[[4, 4, 5],
        [6, 6, 5],
        [4, 4, 6],
        [5, 4, 3],
        [3, 5, 6]]])

In [146]:
x.reshape(1,3,5)

array([[[4, 4, 5, 6, 6],
        [5, 4, 4, 6, 5],
        [4, 3, 3, 5, 6]]])

In [150]:
x.reshape(3,5)

array([[4, 4, 5, 6, 6],
       [5, 4, 4, 6, 5],
       [4, 3, 3, 5, 6]])

In [147]:
x.reshape(5,4)
#we can only reshape array of size  which should not extends size of the original array -->15

ValueError: cannot reshape array of size 15 into shape (5,4)

In [151]:
x.max()

6

In [182]:
x = np.random.randint(2,15,(5,5))

In [155]:
x

array([[11,  8, 14,  3, 14],
       [ 5,  6, 14,  5, 12],
       [12, 12,  2,  6,  3],
       [ 8,  9,  8,  3,  5],
       [12, 10,  7, 10,  7]])

In [156]:
x[0,1]

8

In [157]:
x[0,1] = 100

In [158]:
x

array([[ 11, 100,  14,   3,  14],
       [  5,   6,  14,   5,  12],
       [ 12,  12,   2,   6,   3],
       [  8,   9,   8,   3,   5],
       [ 12,  10,   7,  10,   7]])

In [167]:
mat = np.random.randint(1,4,(3,3))

In [168]:
mat

array([[1, 3, 1],
       [3, 3, 3],
       [2, 1, 1]])

In [169]:
mat1 = np.random.randint(1,4,(3,3))

In [170]:
mat1

array([[1, 2, 3],
       [3, 3, 1],
       [3, 2, 1]])

In [171]:
mat*mat1
#element wise multiplication


array([[1, 6, 3],
       [9, 9, 3],
       [6, 2, 1]])

In [172]:
# to get matrix multiplication we need to use "@"

mat @ mat1

array([[13, 13,  7],
       [21, 21, 15],
       [ 8,  9,  8]])

In [173]:
1/0

ZeroDivisionError: division by zero

In [183]:
x = np.random.randint(2,15,(5,3))

In [184]:
x/0
#inf --> infinity

/tmp/ipykernel_97581/873822677.py:1: RuntimeWarning: divide by zero encountered in true_divide
  x/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [185]:
x.T

array([[ 7,  9, 14,  5,  8],
       [ 4, 10,  6,  5,  5],
       [13, 13,  7,  8,  4]])

In [186]:
x

array([[ 7,  4, 13],
       [ 9, 10, 13],
       [14,  6,  7],
       [ 5,  5,  8],
       [ 8,  5,  4]])

In [187]:
x ** 2

array([[ 49,  16, 169],
       [ 81, 100, 169],
       [196,  36,  49],
       [ 25,  25,  64],
       [ 64,  25,  16]])

In [188]:
#find exponent of all element
np.exp(x)

array([[1.09663316e+03, 5.45981500e+01, 4.42413392e+05],
       [8.10308393e+03, 2.20264658e+04, 4.42413392e+05],
       [1.20260428e+06, 4.03428793e+02, 1.09663316e+03],
       [1.48413159e+02, 1.48413159e+02, 2.98095799e+03],
       [2.98095799e+03, 1.48413159e+02, 5.45981500e+01]])

In [189]:
#find log of all the array

np.log10(x)

array([[0.84509804, 0.60205999, 1.11394335],
       [0.95424251, 1.        , 1.11394335],
       [1.14612804, 0.77815125, 0.84509804],
       [0.69897   , 0.69897   , 0.90308999],
       [0.90308999, 0.69897   , 0.60205999]])

In [190]:
#squareroot of element
np.sqrt(x)

array([[2.64575131, 2.        , 3.60555128],
       [3.        , 3.16227766, 3.60555128],
       [3.74165739, 2.44948974, 2.64575131],
       [2.23606798, 2.23606798, 2.82842712],
       [2.82842712, 2.23606798, 2.        ]])

In [191]:
# pi value
np.pi

3.141592653589793

In [192]:
np.sin(90)

0.8939966636005579